#!/bin/sh -e

case "$1" in
  purge)
  rm -f /etc/modules
  ;;
esac

# Automatically added by dh_installinit/12.9ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d kmod remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinitramfs/12.9ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x /usr/sbin/update-initramfs ] && [ -e /etc/initramfs-tools/initramfs.conf ]; then
		update-initramfs -u
	fi
fi
# End automatically added section


exit 0
